- name: Lab Machine Initial Playbook
  hosts: lab
  tasks:
  - import_tasks: license_machine.yml
  - import_tasks: add_lab_user.yml
  - import_tasks: install_software.yml

  - name: Change the hostname
    ansible.windows.win_hostname:
      name: "{{ inventory_hostname }}"
    register: res    

  - name: Run Windows Update
    ansible.windows.win_updates:
      category_names: '*'
      reboot: yes

  # - name: Reboot one last time for good measure
  #   ansible.windows.win_reboot:
  #   when: res.reboot_required