- name: Tool Machine Initial Playbook
  strategy: free
  hosts: tool_machines, laptops

  tasks:
  - import_tasks: install_tool_software.yml

  - name: Change the hostname
    ansible.windows.win_hostname:
      name: "{{ inventory_hostname }}"
    register: res

  - name: Run Windows Update
    ansible.windows.win_updates:
      category_names: '*'
      reboot: yes

  - name: Reboot one last time for good measure
    ansible.windows.win_reboot:
    when: res.reboot_required
