- name: General system updates playbook
  strategy: free
  hosts: lab, tool_machines, laptops
  tasks:
   - name: Run chocolatey updates and update all installed packages
     chocolatey.chocolatey.win_chocolatey:
       name: all
       state: latest
       source: "{{ choco_repo }}"

   - name: Run windows update, install all updates, and reboot as many times as needed
     ansible.windows.win_updates:
       category_names: '*'
       reboot: yes

